[package]
name = "kae"
version = "0.1.0"
authors = ["Aaron Schlesinger <aaron@ecomaz.net>"]
edition = "2018"

[dependencies]
kube = {version = "0.16.1", features = ["openapi"]}
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
clap = { version = "2.33.0", features = ["suggestions", "color"]}

